It=['Amazon','Google','Microsoft','TCS','Crest']

print("First Company:-")
print(It[0])
print("Middle Company:-")
print(It[int(len(It)/2)])
print("Last Company:-")
print(It[len(It)-1])
print("Insert At Second Position")
It.insert(2,'Accenture')
print(It)
print("Insert At Last Position")
It.append('Apple')
print(It)
print("Reverse the list inndescdending order ")
It.sort(reverse=True)
print(It)
print("Remove the last company from the list")
It.remove(It[len(It)-1])
print(It)
It.clear()
print("Destroyes It Company  list")
print(It)
